# SZC-LAMBDA-IMAGE — Container-Image Lambdas Require Billed ECR Storage
#
# An image package needs an ECR repository, billed per GB-month after the first year. Zip packaging has no storage charge.
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	resource.Type == "AWS::Lambda::Function"
	resource.Properties.PackageType == "Image"

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Properties.PackageType", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-LAMBDA-IMAGE)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: An image package needs an ECR repository, billed per GB-month after the first year. Zip packaging has no storage charge.", [name]),
	}
}
