# SZC-SFN-EXPRESS — Express Workflows Have No Free Tier
#
# Billed per request and per GB-second. Standard has 4,000 free transitions a month, which is why batch uses Standard (PED D4).
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	resource.Type == "AWS::StepFunctions::StateMachine"
	resource.Properties.StateMachineType == "EXPRESS"

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Properties.StateMachineType", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-SFN-EXPRESS)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: Billed per request and per GB-second. Standard has 4,000 free transitions a month, which is why batch uses Standard (PED D4).", [name]),
	}
}
