/**
 * The port, diffed against the oracle on 4,897 real strings.
 *
 * ADR-001: "the differential test is the real deliverable: it converts a rewrite, which
 * would silently lose hard-won behaviour, into a verified migration." This is that test
 * at the function level, and it is the only reason to believe the regexes in
 * `normalize.ts` are right — none of them is correct by inspection.
 *
 * The corpus is every title and credit in the seed catalog, every line of every golden
 * case, and a short list of adversarial strings. It is generated by
 * `tools/oracle-py/differential.py` and committed, so the oracle does not have to be
 * runnable for this to run: the port is checked against a recording of a frozen
 * implementation, which is exactly what a frozen implementation is for.
 *
 * When this fails, the failure message names the input and the function. That matters
 * more than it sounds — a divergence on one Cyrillic title out of 4,897 strings is
 * otherwise a needle in 3 MB of JSON.
 */

import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import {
  dedupeKey,
  fold,
  hasVersionAnnotation,
  normalizeArtist,
  normalizeDocument,
  normalizeIsrc,
  parseDuration,
  splitArtistCredits,
  splitFeatured,
  stripQualifiers,
  tokens,
} from '../src/normalize.js'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')
const FIXTURE = resolve(repoRoot, 'golden', 'diff', 'normalize.jsonl')

interface OracleCase {
  readonly input: string
  readonly normalize_document: string
  readonly fold: string
  readonly tokens: string[]
  readonly strip_qualifiers: {
    readonly base: string
    readonly qualifiers: string[]
    readonly featured: string[]
    readonly version_label: string | null
  }
  readonly normalize_artist: string
  readonly split_artist_credits: { readonly primary: string; readonly featured: string[] }
  readonly split_featured: string[]
  readonly has_version_annotation: boolean
  readonly normalize_isrc: string | null
  readonly parse_duration: number | null
  readonly dedupe_key: string
}

const cases: OracleCase[] = readFileSync(FIXTURE, 'utf8')
  .split('\n')
  .filter(line => line.trim() !== '' && !line.startsWith('//'))
  .map(line => JSON.parse(line) as OracleCase)

/**
 * Compare one function across the whole corpus, reporting every divergence at once.
 *
 * Reporting the first failure only would mean one fix, one rerun, one more failure —
 * and the shape of a Unicode bug is a hundred inputs failing for the same reason, which
 * is visible in a list and invisible one at a time.
 */
/**
 * Serialize with keys sorted, at every depth.
 *
 * Plain `JSON.stringify` compares key *order*, and the oracle's fixture is written with
 * `sort_keys=True` while a TypeScript object literal keeps the order it was written in.
 * Comparing those directly reported 4,897 divergences out of 4,897 on two functions
 * that were in fact identical — a harness bug that looks exactly like a total port
 * failure, which is the most expensive kind of false alarm there is.
 */
function canonical(value: unknown): string {
  return JSON.stringify(value, (_key, v: unknown) => {
    if (v === null || typeof v !== 'object' || Array.isArray(v)) return v
    const record = v as Record<string, unknown>
    return Object.fromEntries(
      Object.keys(record)
        .sort()
        .map(k => [k, record[k]]),
    )
  })
}

function diff<T>(name: string, mine: (input: string) => T, theirs: (c: OracleCase) => T): void {
  const wrong: string[] = []
  for (const c of cases) {
    const expected = theirs(c)
    const actual = mine(c.input)
    if (canonical(actual) !== canonical(expected)) {
      wrong.push(
        `  ${JSON.stringify(c.input)}\n    oracle: ${JSON.stringify(expected)}\n    port:   ${JSON.stringify(actual)}`,
      )
    }
  }
  expect(
    wrong.length,
    `${name} diverges from the oracle on ${wrong.length} of ${cases.length} inputs:\n${wrong.slice(0, 12).join('\n')}`,
  ).toBe(0)
}

describe('the corpus itself', () => {
  it('is big enough to be worth anything', () => {
    // The control. Every assertion below reports by absence, so a fixture that failed
    // to load would make the whole suite pass while comparing nothing.
    expect(cases.length).toBeGreaterThanOrEqual(1000)
  })

  it('contains the scripts the port is most likely to break', () => {
    const everything = cases.map(c => c.input).join('\n')
    for (const probe of ['Печаль', '最後的戰役', 'Björk', 'فيروز']) {
      expect(everything).toContain(probe)
    }
  })
})

describe('packages/core matches tools/oracle-py', () => {
  it('normalizeDocument', () => {
    diff('normalizeDocument', normalizeDocument, c => c.normalize_document)
  })

  it('fold', () => {
    // The one most likely to be wrong. Python's `[^\w\s]` keeps Cyrillic and Greek;
    // JavaScript's ASCII-only `\w` would strip them, folding "Печаль" to "".
    diff('fold', fold, c => c.fold)
  })

  it('tokens', () => {
    diff('tokens', tokens, c => c.tokens)
  })

  it('stripQualifiers', () => {
    diff(
      'stripQualifiers',
      input => {
        const { base, qualifiers, featured, versionLabel } = stripQualifiers(input)
        return {
          base,
          qualifiers: [...qualifiers].sort(),
          featured,
          version_label: versionLabel,
        }
      },
      c => c.strip_qualifiers,
    )
  })

  it('normalizeArtist', () => {
    diff('normalizeArtist', normalizeArtist, c => c.normalize_artist)
  })

  it('splitArtistCredits', () => {
    diff(
      'splitArtistCredits',
      input => {
        const [primary, featured] = splitArtistCredits(input)
        return { primary, featured }
      },
      c => c.split_artist_credits,
    )
  })

  it('splitFeatured', () => {
    diff('splitFeatured', splitFeatured, c => c.split_featured)
  })

  it('hasVersionAnnotation', () => {
    diff('hasVersionAnnotation', hasVersionAnnotation, c => c.has_version_annotation)
  })

  it('normalizeIsrc', () => {
    diff('normalizeIsrc', normalizeIsrc, c => c.normalize_isrc)
  })

  it('parseDuration', () => {
    diff('parseDuration', parseDuration, c => c.parse_duration)
  })

  it('dedupeKey', () => {
    diff(
      'dedupeKey',
      input => dedupeKey(input, input, stripQualifiers(input).qualifiers),
      c => c.dedupe_key,
    )
  })
})
