# SZC-DDB-ONDEMAND — PAY_PER_REQUEST DynamoDB Is Billed From The First Request
#
# The free allowance is 25 WCU/25 RCU of PROVISIONED capacity, shared account-wide across every table and index (PED D6).
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	types := {"AWS::DynamoDB::Table", "AWS::DynamoDB::GlobalTable"}
	types[resource.Type]
	resource.Properties.BillingMode == "PAY_PER_REQUEST"

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Properties.BillingMode", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-DDB-ONDEMAND)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: The free allowance is 25 WCU/25 RCU of PROVISIONED capacity, shared account-wide across every table and index (PED D6).", [name]),
	}
}
