# SZC-LAMBDA-VPC — Lambda In A VPC Pulls In A NAT Gateway
#
# A VPC-attached function needs an ENI, and egress from it needs a NAT gateway — the $32/month charge behind a property nobody reads.
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	resource.Type == "AWS::Lambda::Function"
	resource.Properties.VpcConfig

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Properties.VpcConfig", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-LAMBDA-VPC)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: A VPC-attached function needs an ENI, and egress from it needs a NAT gateway — the $32/month charge behind a property nobody reads.", [name]),
	}
}
