# SZC-S3-LIFECYCLE — A Bucket Without A Lifecycle Rule Never Expires Anything
#
# S3 is credits-only for accounts opened after 2025-07-15, so unexpired objects become a recurring charge once credits run out.
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	resource.Type == "AWS::S3::Bucket"
	not resource.Properties.LifecycleConfiguration.Rules

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Properties", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-S3-LIFECYCLE)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: S3 is credits-only for accounts opened after 2025-07-15, so unexpired objects become a recurring charge once credits run out.", [name]),
	}
}
