# SZC-ALARM-BUDGET — More Than 10 Alarms Is Billed Per Alarm
#
# 10 alarms are free account-wide across all three environments; the next one costs $0.10/month and so does every one after it (PED S11).
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	resource.Type == "AWS::CloudWatch::Alarm"
	alarms := [n | input.document[i].Resources[n].Type == "AWS::CloudWatch::Alarm"]
	count(alarms) > 10

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Type", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-ALARM-BUDGET)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: 10 alarms are free account-wide across all three environments; the next one costs $0.10/month and so does every one after it (PED S11).", [name]),
	}
}
