# SZC-NAT — NAT Gateway Is Never Free
#
# $0.045/hour plus $0.045/GB processed, billed from creation with no free tier — about $32/month for existing.
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	banned := {"AWS::EC2::NatGateway"}
	banned[resource.Type]

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Type", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-NAT)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: $0.045/hour plus $0.045/GB processed, billed from creation with no free tier — about $32/month for existing.", [name]),
	}
}
