# SZC-DDB-PITR — Point-In-Time Recovery Is Billed Per GB Of Backup
#
# $0.20 per GB-month of continuous backup, never covered by the free tier. This data is reconstructible from the source text.
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	resource.Type == "AWS::DynamoDB::Table"
	resource.Properties.PointInTimeRecoverySpecification.PointInTimeRecoveryEnabled == true

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Properties.PointInTimeRecoverySpecification", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-DDB-PITR)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: $0.20 per GB-month of continuous backup, never covered by the free tier. This data is reconstructible from the source text.", [name]),
	}
}
