# SZC-WAF — Standalone WAF Is Billed Per ACL And Per Rule
#
# $5/month per web ACL plus $1 per rule. Prod gets WAF bundled free with the CloudFront flat-rate plan (PED D2).
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	banned := {"AWS::WAFv2::WebACL", "AWS::WAFv2::RuleGroup", "AWS::WAF::WebACL"}
	banned[resource.Type]

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Type", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-WAF)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: $5/month per web ACL plus $1 per rule. Prod gets WAF bundled free with the CloudFront flat-rate plan (PED D2).", [name]),
	}
}
