# SZC-BANNED-SERVICE-IAM — IAM Grants For Services With No Free Tier
#
# Bedrock, Textract, Rekognition, Athena, Cost Explorer, FIS and SES bill per call or per token. A grant is how one of them ends up being called.
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

# Actions live at different depths in Policy and Role, and may be a string or a
# list. Walking the whole resource is the only form that catches both without
# enumerating every shape CloudFormation allows.
walk_actions(resource) = action {
	walk(resource, [_, value])
	is_string(value.Action)
	action := value.Action
}

walk_actions(resource) = action {
	walk(resource, [_, value])
	is_array(value.Action)
	action := value.Action[_]
}

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	types := {"AWS::IAM::Policy", "AWS::IAM::Role"}
	types[resource.Type]
	banned := {"bedrock", "textract", "rekognition", "athena", "ce", "fis", "ses", "comprehend"}
	action := walk_actions(resource)
	service := split(action, ":")[0]
	banned[lower(service)]

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Properties", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-BANNED-SERVICE-IAM)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: Bedrock, Textract, Rekognition, Athena, Cost Explorer, FIS and SES bill per call or per token. A grant is how one of them ends up being called.", [name]),
	}
}
