# SZC-ECR — ECR Storage Is Billed Per GB-Month
#
# Only a 12-month, 500MB free allowance, and a single image is hundreds of megabytes.
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	banned := {"AWS::ECR::Repository"}
	banned[resource.Type]

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Type", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-ECR)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: Only a 12-month, 500MB free allowance, and a single image is hundreds of megabytes.", [name]),
	}
}
