# SZC-SECRETS-MANAGER — Secrets Manager Costs $0.40 Per Secret Per Month
#
# At 10k users holding a refresh token each that is roughly $4,000/month; SSM Parameter Store standard tier is free (PED D10-11).
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	banned := {"AWS::SecretsManager::Secret"}
	banned[resource.Type]

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Type", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-SECRETS-MANAGER)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: At 10k users holding a refresh token each that is roughly $4,000/month; SSM Parameter Store standard tier is free (PED D10-11).", [name]),
	}
}
