# SZC-SYNTHETICS — Synthetics Canaries Are Billed Per Run
#
# $0.0012 per run — about $5/month at one-minute intervals — and each canary also eats the 10-metric and 10-alarm allowances.
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	banned := {"AWS::Synthetics::Canary"}
	banned[resource.Type]

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Type", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-SYNTHETICS)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: $0.0012 per run — about $5/month at one-minute intervals — and each canary also eats the 10-metric and 10-alarm allowances.", [name]),
	}
}
