# SZC-AUTOSCALING — Application Auto Scaling Creates CloudWatch Alarms Outside The Template
#
# Target-tracking policies create alarms at runtime, in the account, against a 10-alarm free allowance that already has 7 budgeted — where no template-shaped gate can see them (ADR-013).
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	markers := {m |
		banned := {"AWS::ApplicationAutoScaling::ScalableTarget", "AWS::ApplicationAutoScaling::ScalingPolicy"}
		banned[resource.Type]
		m := "autoscaling-resource"
	} | {m |
		walk(resource.Properties, [path, _])
		contains(sprintf("%v", [path]), "CapacityAutoScalingSettings")
		m := "inline-autoscaling-settings"
	}
	count(markers) > 0

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-AUTOSCALING)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: Target-tracking policies create alarms at runtime, in the account, against a 10-alarm free allowance that already has 7 budgeted — where no template-shaped gate can see them (ADR-013).", [name]),
	}
}
