# SZC-LAMBDA-PROVISIONED — Provisioned Concurrency Leaves The Free Allowance
#
# Billed hourly for the reservation AND removes the function from the always-free Lambda allowance, so it costs twice.
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	types := {"AWS::Lambda::Version", "AWS::Lambda::Alias"}
	types[resource.Type]
	resource.Properties.ProvisionedConcurrencyConfig

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Properties.ProvisionedConcurrencyConfig", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-LAMBDA-PROVISIONED)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: Billed hourly for the reservation AND removes the function from the always-free Lambda allowance, so it costs twice.", [name]),
	}
}
