# SZC-KMS-CMK — A Customer-Managed KMS Key Costs $1/Month
#
# $1 per key per month before a single request. The token vault uses an AES-GCM data key in an SSM SecureString instead (PED D7).
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	banned := {"AWS::KMS::Key"}
	banned[resource.Type]

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Type", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-KMS-CMK)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: $1 per key per month before a single request. The token vault uses an AES-GCM data key in an SSM SecureString instead (PED D7).", [name]),
	}
}
