# SZC-GLUE — No Glue Option Reaches $0
#
# The cheapest Python shell job bills 1/16 DPU-hour at a one-minute minimum. The Data Catalog is free and is all this project uses (PED D8).
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	banned := {"AWS::Glue::Job", "AWS::Glue::Crawler", "AWS::Glue::Trigger"}
	banned[resource.Type]

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Type", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-GLUE)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: The cheapest Python shell job bills 1/16 DPU-hour at a one-minute minimum. The Data Catalog is free and is all this project uses (PED D8).", [name]),
	}
}
