# SZC-LOG-RETENTION — A Log Group Without Retention Is A Bill That Grows
#
# The 5GB free allowance covers ingest only; stored logs accrue at $0.03 per GB-month forever.
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	resource.Type == "AWS::Logs::LogGroup"
	not resource.Properties.RetentionInDays

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Properties", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-LOG-RETENTION)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: The 5GB free allowance covers ingest only; stored logs accrue at $0.03 per GB-month forever.", [name]),
	}
}
