# SZC-ROUTE53 — A Hosted Zone Costs $0.50/Month Plus Queries
#
# Hosted zones appear in no free tier. The CloudFront default domain costs nothing.
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	banned := {"AWS::Route53::HostedZone"}
	banned[resource.Type]

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Type", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-ROUTE53)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: Hosted zones appear in no free tier. The CloudFront default domain costs nothing.", [name]),
	}
}
