# SZC-APIGW — API Gateway Is Credits-Only On A Post-2025-07-15 Account
#
# Its free tier is 12-month/credits-only for accounts opened after 2025-07-15. Lambda Function URLs behind CloudFront are always free (PED D1).
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	banned := {"AWS::ApiGateway::RestApi", "AWS::ApiGatewayV2::Api", "AWS::Serverless::Api"}
	banned[resource.Type]

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Type", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-APIGW)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: Its free tier is 12-month/credits-only for accounts opened after 2025-07-15. Lambda Function URLs behind CloudFront are always free (PED D1).", [name]),
	}
}
