/**
 * Two artifacts, and the split between them is the whole filing decision.
 *
 * **The manifest** is the full plan: every image, every line of text drawn on it, the
 * songs the extractor should return. It is what M2-05's evaluation harness reads, and at
 * roughly 2.5 MB it is generated into `golden/ocr-generated/` beside the images rather
 * than committed. M2-01 keeps the images out of git; a multi-megabyte JSON file that is
 * rewritten whole whenever the seed changes belongs out with them, because nobody would
 * read its diff and a diff nobody reads is not review.
 *
 * **The summary** is committed, and it is about four kilobytes. It carries exactly the
 * facts M2-01 asks for — how many images of each class, which fonts drew them and under
 * what licence, how much of the seed they can draw — plus a SHA-256 of the full manifest.
 *
 * That digest is the determinism proof, and it is a stronger one than a readable diff.
 * Rebuilding the corpus and comparing one hash asserts that all 620 images, every line of
 * text and every augmentation parameter came out bit-identical. An eye passing over a
 * 2.5 MB diff asserts that someone scrolled.
 *
 * The licence record is read from the installed packages' own metadata for the same
 * reason truth is read from the seed: a hand-written list stops being true the first time
 * somebody swaps a font and forgets.
 */

import { createHash } from 'node:crypto'

import { coverageReport, type CoverageReport, type Font } from './fonts.js'
import {
  IMAGE_CLASSES,
  MAX_ROTATION_DEG,
  OCR_CORPUS_SEED,
  type ImageClass,
  type ImageSpec,
} from './plan.js'

/** One font's licence, as recorded for the corpus. */
export interface FontRecord {
  readonly pkg: string
  readonly family: string
  readonly category: string
  readonly licence: string
  readonly attribution: string
}

export interface Manifest {
  readonly $comment: string
  readonly seed: number
  readonly images: readonly ImageSpec[]
}

/** How many images carry each augmentation. The evidence for M2-01's third done_when. */
export interface AugmentationTally {
  readonly rotated: number
  readonly maxAbsRotationDeg: number
  readonly perspective: number
  readonly blurred: number
  readonly glare: number
  readonly ruledPaper: number
  readonly struckLines: number
  readonly jpegCompressed: number
  readonly minJpegQuality: number
}

export interface Summary {
  readonly $comment: string
  readonly seed: number
  readonly maxRotationDeg: number
  readonly counts: Readonly<Record<string, number>>
  readonly augmentations: AugmentationTally
  readonly fonts: readonly FontRecord[]
  readonly coverage: CoverageReport
  readonly manifestSha256: string
}

const MANIFEST_COMMENT =
  'GENERATED by tools/golden-images — do not edit, and do not commit. Ground truth is ' +
  'derived from golden/seed/recordings.jsonl, never from OCR output, which is what makes ' +
  'this a test rather than a recording of current behaviour. Each line carries the exact ' +
  'text drawn on it, which is what CER and WER are measured against; `songTruth` is what ' +
  'the extractor should return and excludes crossed-out lines, which OCR can still read. ' +
  'Rebuild with `make golden`.'

const SUMMARY_COMMENT =
  'GENERATED by tools/golden-images — do not edit. The committed half of the OCR golden ' +
  'set: counts, the font licence record, seed coverage, and a SHA-256 of the full ' +
  'manifest. The manifest itself and the images are rebuilt into golden/ocr-generated/ ' +
  'by `make golden` and are never committed. `make golden-check` rebuilds the plan and ' +
  'compares this file byte for byte, so a changed digest means the corpus changed.'

export function buildManifest(specs: readonly ImageSpec[], seed = OCR_CORPUS_SEED): Manifest {
  return { $comment: MANIFEST_COMMENT, seed, images: specs }
}

/** The manifest's bytes. Two-space JSON, matching `golden/extraction/generated.json`. */
export function serialize(manifest: Manifest): string {
  return `${JSON.stringify(manifest, null, 2)}\n`
}

function tally(specs: readonly ImageSpec[]): AugmentationTally {
  const quality = specs.map(spec => spec.augmentation.jpegQuality)
  return {
    rotated: specs.filter(spec => spec.augmentation.rotationDeg !== 0).length,
    maxAbsRotationDeg: Math.max(...specs.map(spec => Math.abs(spec.augmentation.rotationDeg))),
    perspective: specs.filter(spec => spec.augmentation.perspectiveDeg !== 0).length,
    blurred: specs.filter(spec => spec.augmentation.blurPx > 0).length,
    glare: specs.filter(spec => spec.augmentation.glare !== null).length,
    ruledPaper: specs.filter(spec => spec.augmentation.ruledPaper).length,
    struckLines: specs.reduce(
      (total, spec) => total + spec.lines.filter(line => line.struck).length,
      0,
    ),
    jpegCompressed: quality.filter(value => value < 100).length,
    minJpegQuality: Math.min(...quality),
  }
}

export function buildSummary(
  manifest: Manifest,
  fonts: readonly Font[],
  seedTexts: readonly string[],
): Summary {
  const specs = manifest.images
  const counts: Record<string, number> = {}
  for (const imageClass of IMAGE_CLASSES) {
    counts[imageClass] = specs.filter(spec => spec.imageClass === imageClass).length
  }
  counts['total'] = specs.length

  return {
    $comment: SUMMARY_COMMENT,
    seed: manifest.seed,
    maxRotationDeg: MAX_ROTATION_DEG,
    counts,
    augmentations: tally(specs),
    fonts: [...fonts]
      .map(font => ({
        pkg: font.pkg,
        family: font.family,
        category: font.category,
        licence: font.licence,
        attribution: font.attribution,
      }))
      .sort((a, b) => a.pkg.localeCompare(b.pkg)),
    coverage: coverageReport(fonts, seedTexts),
    manifestSha256: sha256(serialize(manifest)),
  }
}

export function serializeSummary(summary: Summary): string {
  return `${JSON.stringify(summary, null, 2)}\n`
}

/** Node's digest, not the core's: this is a build tool and never runs on a device. */
export function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex')
}

/** How many images of each class a manifest holds. */
export function countsByClass(manifest: Manifest): Record<ImageClass, number> {
  const counts = {} as Record<ImageClass, number>
  for (const imageClass of IMAGE_CLASSES) {
    counts[imageClass] = manifest.images.filter(spec => spec.imageClass === imageClass).length
  }
  return counts
}
