# SZC-EVENTBUS — Custom EventBridge Buses Have No Free Tier At All
#
# $1 per million events published; only AWS-service management events are free. SNS gives a million publishes a month free (PED D3).
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	banned := {"AWS::Events::EventBus"}
	banned[resource.Type]

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Type", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-EVENTBUS)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: $1 per million events published; only AWS-service management events are free. SNS gives a million publishes a month free (PED D3).", [name]),
	}
}
