# SZC-SQS-ESM — An Idle SQS Poller Spends The Request Allowance
#
# A 20-second long poll makes ~130k requests/month doing nothing, and Lambda runs up to five pollers per mapping (PED D5).
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	resource.Type == "AWS::Lambda::EventSourceMapping"
	arn := resource.Properties.EventSourceArn
	contains(lower(json.marshal(arn)), "sqs")

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Properties.EventSourceArn", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-SQS-ESM)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: A 20-second long poll makes ~130k requests/month doing nothing, and Lambda runs up to five pollers per mapping (PED D5).", [name]),
	}
}
