#!/usr/bin/env node
/**
 * Render `account-bootstrap.yaml` from `template.ts`.
 *
 *   pnpm -C infra exec tsx bootstrap/generate.ts            # write it
 *   pnpm -C infra exec tsx bootstrap/generate.ts --check     # fail if stale
 *
 * `--check` is what `make preflight` runs. The template is the one file a human uploads
 * by hand, so the version committed and reviewed has to be the version built from the
 * deny list the tests assert against — otherwise the review covers a file nobody
 * generated from the thing that was checked.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { stringify } from 'yaml'
import { buildTemplate } from './template.js'

const HERE = dirname(fileURLToPath(import.meta.url))
export const TEMPLATE_PATH = join(HERE, 'account-bootstrap.yaml')

const BANNER = [
  '# Setlist account bootstrap.',
  '#',
  '# GENERATED from infra/bootstrap/template.ts. Do not edit this file: run',
  '#   pnpm -C infra exec tsx bootstrap/generate.ts',
  '# and commit the result. `make preflight` fails if the two disagree.',
  '#',
  '# Generated rather than hand-written because the deny list below has to be checked',
  '# against infra/free-tier/budget.yaml, and a test that parsed CloudFormation',
  '# shorthand to do it would be testing a YAML parser as much as a policy.',
  '#',
  '# Upload this in the CloudFormation console — see docs/hitl/SESSION-1.md section 4.',
  '# It contains no account id, ARN or email: all three are parameters.',
  '',
].join('\n')

export function render(): string {
  // lineWidth 0 disables folding. A folded `Fn::Sub` string is still valid YAML, but it
  // is unreadable in a console diff, and this file is read by a human before it is
  // uploaded.
  //
  // aliasDuplicateObjects false matters more than it looks: the two budget actions
  // share one definition object, and the serialiser would emit the second as a YAML
  // alias (`*a1`). CloudFormation rejects aliases outright, so the stack would fail at
  // upload — found by cfn-lint W1101.
  return `${BANNER}${stringify(buildTemplate(), {
    lineWidth: 0,
    indent: 2,
    aliasDuplicateObjects: false,
  })}`
}

function main(): void {
  const rendered = render()

  if (process.argv.includes('--check')) {
    const current = existsSync(TEMPLATE_PATH) ? readFileSync(TEMPLATE_PATH, 'utf8') : ''
    if (current !== rendered) {
      console.error(
        'account-bootstrap.yaml is out of date with infra/bootstrap/template.ts.\n' +
          'Run: pnpm -C infra exec tsx bootstrap/generate.ts',
      )
      process.exit(1)
    }
    console.log('account-bootstrap.yaml: current')
  } else {
    writeFileSync(TEMPLATE_PATH, rendered, { encoding: 'utf8' })
    console.log(`account-bootstrap.yaml: written (${rendered.split('\n').length} lines)`)
  }
}

// Only when run, never when imported. `infra/test/bootstrap.test.ts` imports `render`
// to assert the committed file matches it — and while this ran at import time, that
// test WROTE the file it was about to compare, so it could not fail. A staleness check
// that rewrites its own subject is not a check.
if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main()
}
