# SZC-COMPUTE — EC2, RDS And Load Balancers Bill By The Hour
#
# All three bill whether or not anything uses them; the architecture is serverless so that idle costs nothing.
#
# GENERATED by tools/gen_kics_queries.js. Edit the spec there, not this file.
# The same rule is enforced at synth time by infra/nag/rules.ts; a parity test
# asserts the two lists name the same rule ids.

package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	resource := input.document[i].Resources[name]
	banned := {"AWS::EC2::Instance", "AWS::RDS::DBInstance", "AWS::RDS::DBCluster", "AWS::ElasticLoadBalancingV2::LoadBalancer", "AWS::ElasticLoadBalancing::LoadBalancer"}
	banned[resource.Type]

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("Resources.%s.Type", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("Resources.%s should not cost money under profile=zero (SZC-COMPUTE)", [name]),
		"keyActualValue": sprintf("Resources.%s is billable: All three bill whether or not anything uses them; the architecture is serverless so that idle costs nothing.", [name]),
	}
}
